# travis.yml taken from symfony/demo
language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - APP_ENV=test

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit
